### ISSUE TITLE
[Core regression] Freeze or crash when loading save state.

### ISSUE THREAD

**Issue by ofry** [libretro/4do-libretro#16]
Way to reproduce:

1) Launch the game with this core.
2) Go to "Quick menu", save state.
3) All working fine.
4) Load this state. All working fine again...
BUT:
5) Close Retroarch.
6) Open same game.
7) Load state.
8) You will get crash Retroarch.

**Comment by finkler** [comment]
I have the same issue. Any idea what this is about?

**Comment by ofry** [comment]
Wow! This issue is fixed, as I see...

**Comment by ofry** [comment]
Oh, I was too optimistic.

Now game could freeze on certain "tick" (core show 60 FPS, frame counter goes, but game freezes).

If there I press "Esc", RA crashes.

Backtrace:

```
Program received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffcb4b61b30 in ntdll!RtlpNtMakeTemporaryKey ()
   from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
(gdb) bt
#0  0x00007ffcb4b61b30 in ntdll!RtlpNtMakeTemporaryKey ()
   from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#1  0x00007ffcb4b64db2 in ntdll!RtlpNtMakeTemporaryKey ()
   from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#2  0x00007ffcb4b659b0 in ntdll!RtlpNtMakeTemporaryKey ()
   from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#3  0x00007ffcb4b1a56f in ntdll!memset ()
   from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#4  0x00007ffcb2c71cb3 in msvcrt!_setjmp ()
   from /cygdrive/c/Windows/system32/msvcrt.dll
#5  0x00000000071f2521 in retro_unload_game ()
   from /cygdrive/c/retroarch/cores/4do_libretro.dll
#6  0x0000000000402dfa in core_unload_game () at core_impl.c:384
#7  0x000000000040c14f in command_event_deinit_core (reinit=true)
    at command.c:1018
#8  0x000000000040df4e in command_event (cmd=CMD_EVENT_CORE_DEINIT, data=0x0)
    at command.c:2027
#9  0x000000000040579c in rarch_ctl (state=RARCH_CTL_MAIN_DEINIT, data=0x0)
    at retroarch.c:1452
#10 0x0000000000401622 in main_exit (args=0x0) at frontend/frontend.c:61
#11 0x000000000040178d in rarch_main (argc=1, argv=0x51fc920, data=0x0)
    at frontend/frontend.c:140
#12 0x00000000004017bc in SDL_main (argc=1, argv=0x51fc920)
---Type <return> to continue, or q <return> to quit---
```

**Comment by ofry** [comment]
Catch SEGFAULT:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000000da0bc77 in _xbplug_MainDevice ()
   from C:\msys64\home\ofry\retroarch\cores\4do_libretro.dll
(gdb) bt
#0  0x000000000da0bc77 in _xbplug_MainDevice ()
   from C:\msys64\home\ofry\retroarch\cores\4do_libretro.dll
#1  0x000000000da147fe in _xbus_GetPoll ()
   from C:\msys64\home\ofry\retroarch\cores\4do_libretro.dll
#2  0x000000000da06c05 in _arm_Execute ()
   from C:\msys64\home\ofry\retroarch\cores\4do_libretro.dll
#3  0x000000000da03568 in _freedo_Interface ()
   from C:\msys64\home\ofry\retroarch\cores\4do_libretro.dll
#4  0x000000000da0299d in retro_run ()
   from C:\msys64\home\ofry\retroarch\cores\4do_libretro.dll
#5  0x00000000004027b9 in core_run () at core_impl.c:415
#6  0x0000000000407541 in runloop_iterate (sleep_ms=sleep_ms@entry=0x23fde0)
    at retroarch.c:3046
#7  0x00000000004016c0 in rarch_main (argc=<optimized out>,
    argv=<optimized out>, data=0x0) at frontend/frontend.c:129
#8  0x00000000006df0b8 in main_getcmdline ()
#9  0x00000000004013f8 in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:334
#10 0x00000000004014eb in WinMainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:184

```

**Comment by ofry** [comment]
1 more bt:

```
(gdb) bt
#0  0x00007ffcb4aa56bc in ntdll!RtlFreeHeap ()
   from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00007ffcb2c71cb3 in msvcrt!_setjmp ()
   from C:\Windows\system32\msvcrt.dll
#2  0x000000000daa2ae8 in retro_unload_game () at libretro.c:635
#3  0x0000000000402774 in core_unload_game () at core_impl.c:384
#4  0x000000000040bd57 in command_event_deinit_core (reinit=true)
    at command.c:1018
#5  command_event (cmd=cmd@entry=CMD_EVENT_CORE_DEINIT, data=data@entry=0x0)
    at command.c:2027
#6  0x0000000000405630 in rarch_ctl (state=state@entry=RARCH_CTL_MAIN_DEINIT,
    data=data@entry=0x0) at retroarch.c:1452
#7  0x00000000004016fc in main_exit (args=0x0) at frontend/frontend.c:61
#8  rarch_main (argc=<optimized out>, argv=<optimized out>, data=0x0)
    at frontend/frontend.c:140
#9  0x00000000006df0b8 in main_getcmdline ()
#10 0x00000000004013f8 in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:334
#11 0x00000000004014eb in WinMainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:184
(gdb)
```

**Comment by bparker06** [comment]
PR #32 fixes this for me. Note that you will need to create new save states for them to be able to load properly as the saving was broken in addition to the loading.

**Comment by ofry** [comment]
Solved. Big thank you. Will close then. Good luck!
